# Generated by Django 4.2.5 on 2023-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('ND', 'Not Done')], max_length=2),
        ),
    ]
